version: '3.9'

# DailyDevQ 프론트엔드 전용 Docker Compose
# 백엔드는 dailydevq-backend 레포에서 별도 관리

services:
  # Next.js 프론트엔드
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dailydevq-frontend
    environment:
      # Next.js 설정
      NODE_ENV: ${NODE_ENV:-development}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}

      # 백엔드 API 연결 (별도 레포에서 실행 중인 백엔드)
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}

      # 인증 설정
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-dev-nextauth-secret-change-in-production}

      # Vercel Analytics
      NEXT_PUBLIC_VERCEL_ANALYTICS_ID: ${NEXT_PUBLIC_VERCEL_ANALYTICS_ID:-}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - dailydevq-network
    restart: unless-stopped

networks:
  dailydevq-network:
    name: dailydevq-shared
    driver: bridge
